In [1]:
import pandas as pd
df = pd.read_csv("retail_toy_dataset.csv")
df = df.loc[:, ["product_id", "product_name", "description", "list_price"]]
df = df.dropna()
df.head(10)

,product_id,product_name,description,list_price
0,7e8697b5b7cdb5a40daf54caf1435cd5,"Koplow Games Set of 2 D12 12-Sided Rock, Paper...","Rock, paper, scissors is a great way to resolv...",3.56
1,7de8b315b3cb91f3680eb5b88a20dcee,"12""-20"" Schwinn Training Wheels",Turn any small bicycle into an instrument for ...,28.17
2,fb9535c103d7d717f0414b2b111cfaaa,Bicycle Pinochle Jumbo Index Playing Cards - 1...,Purchase includes 1 blue deck and 1 red deck. ...,6.49
3,c73ea622b3be6a3ffa3b0b5490e4929e,Step2 Woodland Adventure Playhouse & Slide,The Step2 Woodland Climber Adventure Playhouse...,499.99
4,dec7bd1f983887650715c6fafaa5b593,Step2 Naturally Playful Welcome Home Playhouse...,Children can play and explore in the Step2 Nat...,600.00
5,74a695e3675efc2aad11ed73c46db29b,Slip N Slide Triple Racer with Slide Boogies,Triple Racer Slip and Slide with Boogie Boards...,37.21
6,3eae5293b56c25f63b47cb8a89fb4813,Hydro Tools Digital Pool/Spa Thermometer,The solar-powered Swimline Floating Digital Th...,15.92
7,ed85bf829a36c67042503ffd9b6ab475,Full Bucket Swing With Coated Chain Toddler Sw...,Safe Kids&Children Full Bucket Swing With Coa...,102.26
8,55820fa53f0583cb637d5cb2b051d78c,Banzai Water Park Splash Zone,Dive into fun in your own backyard with the B...,397.82
9,0e26a9e92e4036bfaa68eb2040a8ec97,Polaris 39-310 5-Liter Zippered Super Bag for ...,Keep your pool water sparkling clean all seaso...,39.47

In [2]:
import asyncpg
from sqlalchemy import create_engine
import psycopg2

async def main():
    # create connection
    conn = await asyncpg.connect('postgresql://postgres:postgres@127.0.0.1/ontology')
    # conn_string = 'postgresql://postgres:postgres@127.0.0.1/ontology'
    # db = create_engine(conn_string)
    # conn = db.connect()
    # conn = psycopg2.connect(
    #    database="ontology",
    #    user='postgres',
    #    password='postgres',
    #    host='127.0.0.1',
    #    port='5432'
    # )
    # conn.autocommit = True
    # cursor = conn.cursor()
    
    # drop table if it already exists
    await conn.execute('''
        DROP TABLE IF EXISTS products CASCADE;
    ''')

    # create table schema
    await conn.execute('''
        CREATE TABLE products(product_id VARCHAR(1024) PRIMARY KEY,
                                product_name TEXT,
                                description TEXT,
                                list_price NUMERIC);
    ''')

    # add csv data into table
    tuples = list(df.itertuples(index=False))
    await conn.copy_records_to_table(
            "products", records=tuples, columns=list(df), timeout=10
    )
    
#     value = await conn.fetch('''
#         select * from products;
#     ''')

    # close connection
    await conn.close()

await main()

In [3]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    separators=[".", "\n"],
    chunk_size=500,
    chunk_overlap=0,
    length_function=len,
)
chunked = []
for index, row in df.iterrows():
    product_id = row["product_id"]
    desc = row["description"]
    splits = text_splitter.create_documents([desc])
    for s in splits:
        r = {"product_id": product_id, "content": s.page_content}
        chunked.append(r)

In [4]:
from langchain.embeddings import OpenAIEmbeddings
import time
import dotenv
import os

dotenv.load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
embeddings_service = OpenAIEmbeddings()


# Helper function to retry failed API requests with exponential backoff.
def retry_with_backoff(func, *args, retry_delay=5, backoff_factor=2, **kwargs):
    max_attempts = 10
    retries = 0
    for i in range(max_attempts):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            print(f"error: {e}")
            retries += 1
            wait = retry_delay * (backoff_factor**retries)
            print(f"Retry after waiting for {wait} seconds...")
            time.sleep(wait)


batch_size = 5
for i in range(0, len(chunked), batch_size):
    request = [x["content"] for x in chunked[i : i + batch_size]]
    response = retry_with_backoff(embeddings_service.embed_documents, request)
    # Store the retrieved vector embeddings for each chunk back.
    for x, e in zip(chunked[i : i + batch_size], response):
        x["embedding"] = e

# Store the generated embeddings in a pandas dataframe.
product_embeddings = pd.DataFrame(chunked)
product_embeddings.head()

,product_id,content,embedding
0,7e8697b5b7cdb5a40daf54caf1435cd5,"Rock, paper, scissors is a great way to resolv...","[-0.008867499727430806, 0.014060657961181383, ..."
1,7e8697b5b7cdb5a40daf54caf1435cd5,". Great for educational games, dice games, boa...","[-0.0013363465225081973, 0.02269774532722539, ..."
2,7de8b315b3cb91f3680eb5b88a20dcee,Turn any small bicycle into an instrument for ...,"[0.019454792134748034, -0.004127374453529148, ..."
3,7de8b315b3cb91f3680eb5b88a20dcee,. Durable Construction: Steel brackets stand u...,"[0.014991591231696418, 0.009261855575828058, -..."
4,7de8b315b3cb91f3680eb5b88a20dcee,. Tools required: Adjustable wrench. www.schwi...,"[0.02521163542924525, -0.001772273162437382, -..."

In [5]:
import numpy as np
from pgvector.asyncpg import register_vector

async def main():
    # create connection
    conn = await asyncpg.connect('postgresql://postgres:postgres@127.0.0.1/ontology')
    # add vector extension
    await conn.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    await register_vector(conn)
    # drop table if exists
    await conn.execute('DROP TABLE IF EXISTS product_embeddings;')
    # Create the `product_embeddings` table to store vector embeddings.
    sql = """CREATE TABLE product_embeddings(
                                product_id VARCHAR(1024) NOT NULL REFERENCES products(product_id),
                                content TEXT,
                                embedding vector(1536));"""
    await conn.execute(sql)
    # Store all the generated embeddings back into the database.
    for index, row in product_embeddings.iterrows():
        await conn.execute(
            "INSERT INTO product_embeddings (product_id, content, embedding) VALUES ($1, $2, $3)",
            row["product_id"],
            row["content"],
            np.array(row["embedding"]),
        )
    await conn.close()
    
await main()

In [6]:
toy = "playing card games"
min_price = 1
max_price = 100
# embed the query
embeddings_service = OpenAIEmbeddings()
qe = embeddings_service.embed_query(toy)
# define matches for results
matches = []
async def main():
    # create connection
    conn = await asyncpg.connect('postgresql://postgres:postgres@127.0.0.1/ontology')
    # set variables
    await register_vector(conn)
    similarity_threshold = 0.1
    num_matches = 50
    # Find similar products to the query using cosine similarity search
    # over all vector embeddings. This new feature is provided by `pgvector`.
    results = await conn.fetch(
            """
            WITH vector_matches AS (
              SELECT product_id, 1 - (embedding <=> $1) AS similarity
              FROM product_embeddings
              WHERE 1 - (embedding <=> $1) > $2
              ORDER BY similarity DESC
              LIMIT $3
            )
            SELECT product_name, list_price, description FROM products
            WHERE product_id IN (SELECT product_id FROM vector_matches)
            AND list_price >= $4 AND list_price <= $5
            """,
            qe,
            similarity_threshold,
            num_matches,
            min_price,
            max_price,
    )

    if len(results) == 0:
        raise Exception("Did not find any results. Adjust the query parameters.")

    for r in results:
        # Collect the description for all the matched similar toy products.
        matches.append(
            {
                "product_name": r["product_name"],
                "description": r["description"],
                "list_price": round(r["list_price"], 2),
            }
        )

    await conn.close()

    
await main()

# Show the results for similar products that matched the user query.
matches = pd.DataFrame(matches)
matches.head(5)

,product_name,description,list_price
0,Cartas Españolas Yoruba Naipes Barajas Espanol...,This listing includes 1 deck of cards. Cartas ...,5.25
1,LANG WINTER MAGIC TIN PLAYING CARDS,Gather with family and friends for laughter an...,14.98
2,Regal Games Easy Read High Contrast Bingo Call...,This Bingo Calling Card Deck is great for call...,6.99
3,1 Deck Hoyle 100% Plastic Standard Poker Playi...,HOYLE 100% PLASTIC CARDS ARE MUCH MORE DURABLE...,6.59
4,1 Deck Bicycle Tragic Royalty Standard Poker P...,Do you have a Goth side? Bicycle Tragic Royalt...,6.14